-- MySQL Script generated by MySQL Workbench
-- ven. 04 oct. 2024 10:57:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema e22007619_db2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e22007619_db2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e22007619_db2` ;
USE `e22007619_db2` ;

-- -----------------------------------------------------
-- Table `e22007619_db2`.`t_compte_cpt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22007619_db2`.`t_compte_cpt` (
  `cpt_username` VARCHAR(120) NOT NULL,
  `cpt_password` CHAR(128) NOT NULL,
  `cpt_actif` CHAR(1) NOT NULL,
  PRIMARY KEY (`cpt_username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22007619_db2`.`t_administrateur_adm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22007619_db2`.`t_administrateur_adm` (
  `cpt_username` VARCHAR(120) NOT NULL,
  `adm_nom` VARCHAR(60) NULL,
  `adm_prenom` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`cpt_username`),
  INDEX `fk_t_administrateur_adm_t_compte_cpt1_idx` (`cpt_username` ASC) VISIBLE,
  CONSTRAINT `fk_t_administrateur_adm_t_compte_cpt1`
    FOREIGN KEY (`cpt_username`)
    REFERENCES `e22007619_db2`.`t_compte_cpt` (`cpt_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22007619_db2`.`t_jury_jry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22007619_db2`.`t_jury_jry` (
  `cpt_username` VARCHAR(120) NOT NULL,
  `jry_nom` VARCHAR(60) NULL,
  `jry_prenom` VARCHAR(60) NOT NULL,
  `jry_description` VARCHAR(200) NOT NULL,
  `jry_biographie` VARCHAR(2000) NOT NULL,
  `jry_url` VARCHAR(300) NULL,
  PRIMARY KEY (`cpt_username`),
  INDEX `fk_t_jury_jry_t_compte_cpt1_idx` (`cpt_username` ASC) VISIBLE,
  CONSTRAINT `fk_t_jury_jry_t_compte_cpt1`
    FOREIGN KEY (`cpt_username`)
    REFERENCES `e22007619_db2`.`t_compte_cpt` (`cpt_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22007619_db2`.`t_actualite_act`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22007619_db2`.`t_actualite_act` (
  `act_id` INT NOT NULL AUTO_INCREMENT,
  `act_titre` VARCHAR(60) NOT NULL,
  `act_texte` VARCHAR(200) NULL,
  `act_date_publication` DATE NOT NULL,
  `act_actif` CHAR(1) NOT NULL,
  `cpt_username` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`act_id`),
  INDEX `fk_t_actualite_act_t_administrateur_adm2_idx` (`cpt_username` ASC) VISIBLE,
  CONSTRAINT `fk_t_actualite_act_t_administrateur_adm2`
    FOREIGN KEY (`cpt_username`)
    REFERENCES `e22007619_db2`.`t_administrateur_adm` (`cpt_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22007619_db2`.`t_categorie_cat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22007619_db2`.`t_categorie_cat` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_nom` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22007619_db2`.`t_concours_cnc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22007619_db2`.`t_concours_cnc` (
  `cnc_id` INT NOT NULL AUTO_INCREMENT,
  `cnc_nom` VARCHAR(60) NOT NULL,
  `cnc_description` VARCHAR(200) NOT NULL,
  `cnc_date_debut` DATE NOT NULL,
  `cnc_nb_jours_candidature` INT NOT NULL,
  `cnc_nb_jours_pre_selection` INT NOT NULL,
  `cnc_nb_jours_selection` INT NOT NULL,
  `cpt_username` VARCHAR(120) NULL,
  PRIMARY KEY (`cnc_id`),
  INDEX `fk_t_concours_cnc_t_administrateur_adm1_idx` (`cpt_username` ASC) VISIBLE,
  CONSTRAINT `fk_t_concours_cnc_t_administrateur_adm1`
    FOREIGN KEY (`cpt_username`)
    REFERENCES `e22007619_db2`.`t_administrateur_adm` (`cpt_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22007619_db2`.`t_candidature_cdt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22007619_db2`.`t_candidature_cdt` (
  `cdt_id` INT NOT NULL AUTO_INCREMENT,
  `cdt_mail` VARCHAR(120) NOT NULL,
  `cdt_nom_candidat` VARCHAR(60) NOT NULL,
  `cdt_prenom_candidat` VARCHAR(60) NOT NULL,
  `cdt_presentation_candidat` VARCHAR(200) NOT NULL,
  `cdt_code_dossier` CHAR(20) NOT NULL,
  `cdt_code_candidat` CHAR(8) NOT NULL,
  `cdt_actif` CHAR(1) NOT NULL,
  `cnc_id` INT NOT NULL,
  `cat_id` INT NOT NULL,
  INDEX `fk_t_candidature_cdt_t_categorie_cat1_idx` (`cat_id` ASC) VISIBLE,
  INDEX `fk_t_candidature_cdt_t_concours_cnc1_idx` (`cnc_id` ASC) VISIBLE,
  PRIMARY KEY (`cdt_id`),
  CONSTRAINT `fk_t_candidature_cdt_t_categorie_cat1`
    FOREIGN KEY (`cat_id`)
    REFERENCES `e22007619_db2`.`t_categorie_cat` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_candidature_cdt_t_concours_cnc1`
    FOREIGN KEY (`cnc_id`)
    REFERENCES `e22007619_db2`.`t_concours_cnc` (`cnc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22007619_db2`.`t_document_doc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22007619_db2`.`t_document_doc` (
  `doc_id` INT NOT NULL AUTO_INCREMENT,
  `doc_nom` VARCHAR(60) NOT NULL,
  `doc_emplacement` VARCHAR(300) NOT NULL,
  `doc_type` VARCHAR(60) NOT NULL,
  `cdt_id` INT NOT NULL,
  PRIMARY KEY (`doc_id`),
  INDEX `fk_t_document_doc_t_candidature_cdt1_idx` (`cdt_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_document_doc_t_candidature_cdt1`
    FOREIGN KEY (`cdt_id`)
    REFERENCES `e22007619_db2`.`t_candidature_cdt` (`cdt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22007619_db2`.`t_fil_fil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22007619_db2`.`t_fil_fil` (
  `fil_id` INT NOT NULL AUTO_INCREMENT,
  `fil_sujet` VARCHAR(60) NOT NULL,
  `cnc_id` INT NOT NULL,
  PRIMARY KEY (`fil_id`),
  INDEX `fk_t_fil_fil_t_concours_cnc1_idx` (`cnc_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_fil_fil_t_concours_cnc1`
    FOREIGN KEY (`cnc_id`)
    REFERENCES `e22007619_db2`.`t_concours_cnc` (`cnc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22007619_db2`.`t_message_msg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22007619_db2`.`t_message_msg` (
  `msg_id` INT NOT NULL AUTO_INCREMENT,
  `msg_message` VARCHAR(45) NOT NULL,
  `fil_id` INT NOT NULL,
  `cpt_username` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`msg_id`),
  INDEX `fk_t_message_msg_t_fil_fil1_idx` (`fil_id` ASC) VISIBLE,
  INDEX `fk_t_message_msg_t_jury_jry1_idx` (`cpt_username` ASC) VISIBLE,
  CONSTRAINT `fk_t_message_msg_t_fil_fil1`
    FOREIGN KEY (`fil_id`)
    REFERENCES `e22007619_db2`.`t_fil_fil` (`fil_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_message_msg_t_jury_jry1`
    FOREIGN KEY (`cpt_username`)
    REFERENCES `e22007619_db2`.`t_jury_jry` (`cpt_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22007619_db2`.`t_notation_nte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22007619_db2`.`t_notation_nte` (
  `nte_note` TINYINT NOT NULL,
  `cpt_username` VARCHAR(120) NOT NULL,
  `cdt_id` INT NOT NULL,
  PRIMARY KEY (`cpt_username`, `cdt_id`),
  INDEX `fk_t_notation_nte_t_jury_jry1_idx` (`cpt_username` ASC) VISIBLE,
  INDEX `fk_t_notation_nte_t_candidature_cdt1_idx` (`cdt_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_notation_nte_t_jury_jry1`
    FOREIGN KEY (`cpt_username`)
    REFERENCES `e22007619_db2`.`t_jury_jry` (`cpt_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_notation_nte_t_candidature_cdt1`
    FOREIGN KEY (`cdt_id`)
    REFERENCES `e22007619_db2`.`t_candidature_cdt` (`cdt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22007619_db2`.`t_comprend_cmp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22007619_db2`.`t_comprend_cmp` (
  `cnc_id` INT NOT NULL,
  `cat_id` INT NOT NULL,
  INDEX `fk_t_partition_prt_t_concours_cnc1_idx` (`cnc_id` ASC) VISIBLE,
  PRIMARY KEY (`cnc_id`, `cat_id`),
  INDEX `fk_t_partition_prt_t_categorie_cat1_idx` (`cat_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_partition_prt_t_concours_cnc1`
    FOREIGN KEY (`cnc_id`)
    REFERENCES `e22007619_db2`.`t_concours_cnc` (`cnc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_partition_prt_t_categorie_cat1`
    FOREIGN KEY (`cat_id`)
    REFERENCES `e22007619_db2`.`t_categorie_cat` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22007619_db2`.`t_juge_jge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22007619_db2`.`t_juge_jge` (
  `cpt_username` VARCHAR(120) NOT NULL,
  `cnc_id` INT NOT NULL,
  INDEX `fk_t_juge_jge_t_concours_cnc1_idx` (`cnc_id` ASC) VISIBLE,
  PRIMARY KEY (`cpt_username`, `cnc_id`),
  INDEX `fk_t_juge_jge_t_jury_jry1_idx` (`cpt_username` ASC) VISIBLE,
  CONSTRAINT `fk_t_juge_jge_t_concours_cnc1`
    FOREIGN KEY (`cnc_id`)
    REFERENCES `e22007619_db2`.`t_concours_cnc` (`cnc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_juge_jge_t_jury_jry1`
    FOREIGN KEY (`cpt_username`)
    REFERENCES `e22007619_db2`.`t_jury_jry` (`cpt_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
